version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME}/student-feedback-frontend:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    image: ${DOCKER_USERNAME}/student-feedback-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/feedback
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: 