services:
  - type: web
    name: student-feedback-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: "30"
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health 