services:
  - type: web
    name: student-feedback-frontend
    env: static
    buildCommand: npm run install-all && cd frontend && DISABLE_ESLINT_PLUGIN=true npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: "false"
      - key: REACT_APP_API_URL
        value: https://student-feedback-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: student-feedback-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: "30"
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://student-feedback-frontend.onrender.com
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health 