name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Backend setup
    - name: Install Backend Dependencies and Generate Lock File
      working-directory: ./backend
      run: |
        npm install
        if [ ! -f "package-lock.json" ]; then
          npm install
        fi

    # Frontend setup
    - name: Install Frontend Dependencies and Generate Lock File
      working-directory: ./frontend
      run: |
        npm install
        if [ ! -f "package-lock.json" ]; then
          npm install
        fi

    - name: Cache Backend node_modules
      uses: actions/cache@v3
      with:
        path: ./backend/node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('./backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Cache Frontend node_modules
      uses: actions/cache@v3
      with:
        path: ./frontend/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('./frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-frontend-

    - name: Run Backend Linting
      working-directory: ./backend
      run: |
        npm run lint || true
        
    - name: Run Frontend Linting
      working-directory: ./frontend
      run: |
        npm run lint || true

    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        npm test || true
      env:
        CI: true
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_EXPIRE: 30d
        JWT_COOKIE_EXPIRE: 30

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: |
        npm test -- --passWithNoTests
      env:
        CI: true

    - name: Build Backend
      working-directory: ./backend
      run: npm run build --if-present

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    # Add package-lock.json files to git if they changed
    - name: Commit package-lock.json files if they changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add **/package-lock.json
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: update package-lock.json files [skip ci]"
      continue-on-error: true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      continue-on-error: true 