name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run Backend Linting
      working-directory: ./backend
      run: |
        npm run lint || true
        
    - name: Run Frontend Linting
      working-directory: ./frontend
      run: |
        npm run lint || true

    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        npm test || true
      env:
        CI: true
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_EXPIRE: 30d
        JWT_COOKIE_EXPIRE: 30

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: |
        npm test -- --passWithNoTests
      env:
        CI: true

    - name: Build Backend
      working-directory: ./backend
      run: npm run build --if-present

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build 